### ISSUE TITLE
CurationEngine (or whatever it's called) / Sufia roadmap

### ISSUE THREAD

**Issue by pbinkley** [pbinkley/HC2015-program#11]
CurationEngine (or whatever it's called) / Sufia roadmap

Suggested by: Justin Coyne
Presenter: Jon Stroop (and Michael J. Giarlo is happy to collab on this)
Format: Breakout or workshop
Audience: All

**Comment by hackartisan** [comment]
+1

**Comment by mjgiarlo** [comment]
I'm wondering what this breakout will offer that the plenary session (#69) wouldn't already, other than more time and space to get feedback on the plenary talk and discuss future directions. Feels half-baked, but if @jpstroop wants to run this and others feel there's a need, I can help out.

**Comment by jpstroop** [comment]
I agree that this seems too similar to #69, and I'd rather participate in that than lead a somewhat redundant session.
