### ISSUE TITLE
Realtime Edge for a Hydra Back-end

### ISSUE THREAD

**Issue by pbinkley** [pbinkley/HC2015-program#20]
Realtime Edge for a Hydra Back-end

Suggested by: Email to hydra-connect from Fred Stein
Presenter: 
Format: ?
Audience: Devs?

**Comment by hackartisan** [comment]
from the email:
Realtime data streaming is a natural complement to Hydra. An Open Source, API-first, approach makes the most sense for the Hydra community. Deciding how to handle realtime, especially at scale, provokes several  business and technical decisions. Fanout’s CEO, Justin Karneges, examines the approaches to realtime enablement. While there are many standards such as WebSockets, WebHooks, Apple Push Notifications (APN), Amazon Simple Notification Service (Amazon SNS), and Google Cloud Messaging (GCM) each one has specific applications and limits. Thus developers will either implement, debug and support all standards or support only a subset. Commercial solutions range from “As a Service” to enterprise licensed proprietary software packages. Commercial solutions, by nature create lock-in both to the technology and the APIs that access the services. The ideal approach is to implement the standards, provide access via public (open) RESTful APIs and release the realtime data messaging software as Open Source.
