### ISSUE TITLE
git run test

### ISSUE THREAD

**Issue by hackartisan** [pbinkley/HC2015-program#44]
Okay here is how it works: Login at poll.gitrun.com (you have to allow it to edit your repos). Once you are logged in you can point it directly at an issue with a URL like http://poll.gitrun.com/pbinkley/HC2015-program/issues/1. View vote totals or click to vote. The way it votes is by just leaving a comment that says simply '+1'; if you do that manually it will also count your vote.

**Comment by hackmastera** [comment]
+1

**Comment by hackmastera** [comment]
+1

**Comment by hackmastera** [comment]
Okay here is how it works: Login at poll.gitrun.com (you have to allow it to edit your repos). Once you are logged in you can point it directly at an issue with a URL like http://poll.gitrun.com/pbinkley/HC2015-program/issues/1. View vote totals or click to vote. The way it votes is by just leaving a comment that says simply '+1'; if you do that manually it will also count your vote.

**Comment by hackartisan** [comment]
I put this info in our meeting notes instead; closing to avoid cluttering actual program proposals.
