### ISSUE TITLE
Hydra: Orientation for New Adopters and Partners. (see also #72) How does the community actuall...

### ISSUE THREAD

**Issue by pbinkley** [pbinkley/HC2015-program#46]
Hydra: Orientation for New Adopters and Partners. How does the community actually work? What are all these gems and heads I hear about? How do I know where to start? How do we contribute back?

Suggested by: Tom Cramer
Presenter:  
Format: Presentation ?
Audience: Mgrs

**Comment by richardGreen** [comment]
#72 processed - covers this ticket too
